const ALLOWED_DOMAIN_KEYWORDS = [
  'ai',
  'artificial intelligence',
  'machine learning',
  'ml',
  'deep learning',
  'llm',
  'transformer',
  'neural',
  'blockchain',
  'web3',
  'smart contract',
  'ethereum',
  'solidity',
  'data science',
  'statistics',
  'regression',
  'classification',
  'clustering',
  'cyber',
  'security',
  'encryption',
  'hash',
  'malware',
  'phishing',
  'zero trust',
  'robot',
  'robotics',
  'iot',
  'sensor',
  'embedded',
  'microcontroller',
  'raspberry pi',
  'arduino',
  'digital india',
  'upi',
  'aadhaar',
  'digilocker',
  'india stack',
  'innovation',
  'emerging tech',
  'quantum',
  'edge computing',
];

export function isInAllowedDomain(q: string): boolean {
  const normalized = q.toLowerCase();
  return ALLOWED_DOMAIN_KEYWORDS.some((keyword) => normalized.includes(keyword));
}
